#!/usr/bin/env python3
"""
convert files generated by Monte Carlo method in 2015 to my format
"""
import argparse
from typing import TextIO


def conv(ranked: TextIO, save2: TextIO, skip_lines: int = 1, pwd_idx: int = 0, rank_idx: int = 1):
    pwd_rank = {}
    for _ in range(skip_lines):
        ranked.readline()
    for line in ranked:
        line = line.strip("\r\n")
        items = line.split("\t")
        pwd = items[pwd_idx]
        rank = items[rank_idx]
        n, _ = pwd_rank.get(pwd, (0, .0))
        pwd_rank[pwd] = (n + 1, float(rank))
    prev_rank = 0
    cracked = 0
    total = sum([n for n, _ in pwd_rank.values()])
    for pwd, (num, rank) in sorted(pwd_rank.items(), key=lambda x: x[1][1]):
        cracked += num
        rank = round(max(rank, prev_rank + 1))
        save2.write(f"{pwd}\t{0.0}\t{num}\t{rank}\t{cracked}\t{cracked / total * 100:5.2f}\n")


def main():
    cli = argparse.ArgumentParser("Monte Carlo 2015 results converter")
    cli.add_argument("-r", "--ranked", dest="ranked", required=True, type=argparse.FileType("r"),
                     help="result generated by Monte Carlo 2015")
    cli.add_argument("-s", "--save", dest="save", required=True, type=argparse.FileType("w"),
                     help="save converted file here")
    cli.add_argument("--skip", dest="skip", required=False, type=int, default=1, help="skip first N lines")
    cli.add_argument("--pwd-idx", dest="pwd_idx", required=False, type=int, default=0,
                     help="which column stores the password")
    cli.add_argument("--rank-idx", dest="rank_idx", required=False, type=int, default=1,
                     help="which column stores the rank")
    args = cli.parse_args()
    conv(args.ranked, save2=args.save, skip_lines=args.skip, pwd_idx=args.pwd_idx, rank_idx=args.rank_idx)


if __name__ == '__main__':
    main()
